# Generated by Django 4.2 on 2023-04-06 16:20

from django.db import migrations

from quotes.service.scrape_quotes import scrape_quotes
from django.contrib.auth.models import User


def fill_db(apps, schema_editor):
    scrape_quotes(User.objects.get(id=1))


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_db)
    ]
